export const INIT = 'INIT'
export const SET_SEARCH_PARAMETER = 'SET_SEARCH_PARAMETER '
export const GET_CURRENT_USER = 'GET_CURRENT_USER'
export const GET_PUSHING = 'GET_PUSHING'
export const DISABLE_PUSHING = 'DISABLE_PUSHING'
export const ENABLE_PUSHING = 'ENABLE_PUSHING'
export const HAS_ACCESS = 'HAS_ACCESS'
export const SIGN_IN = 'SIGN_IN'
export const REMEMBER_TOKEN = 'REMEMBER_TOKEN'

//order
export const GET_ORDER_LIST = 'GET_ORDER_LIST'

//notifications
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS'
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION'
export const SET_PAGINATION_NOTIFICATION = 'SET_PAGINATION_NOTIFICATION'

//news
export const GET_MAIN_NEWS = 'GET_MAIN_NEWS'
export const GET_NEWS = 'GET_NEWS'
export const SET_NEWS_PAGINATION = 'SET_NEWS_PAGINATION'

//masters
export const GET_MAIN_MASTERS = 'GET_MAIN_MASTERS'
export const GET_MASTERS = 'GET_SORTS'
export const GET_MASTER = 'GET_SORT'
export const SET_PAGINATION_MASTERS = 'SET_PAGINATION_SORTS'
export const GET_MASTER_ASSORTMENT = 'GET_MASTER_ASSORTMENT'
export const SET_MASTERS_SORTING = 'SET_SORTS_SORTING'
export const SET_MASTERS_REGION = 'SET_MASTERS_REGION'

//other
export const GLOBAL_LOGOUT = 'GLOBAL_LOGOUT'
export const GET_ORDERS = 'GET_ORDERS'
export const GET_BASKET_ITEMS = 'GET_BASKET_ITEMS'
export const REMOVE_BASKET_ITEM = 'REMOVE_BASKET_ITEM'
export const REMOVE_ALL_BASKET_ITEMS = 'REMOVE_ALL_BASKET_ITEMS'
export const SET_MIDDLE_MENU_TYPE = 'SET_MIDDLE_MENU_TYPE'
export const GET_GLOBAL_USER_INFO = 'GET_GLOBAL_USER_INFO'
export const GET_GLOBAL_LOCATION = 'GET_GLOBAL_LOCATION'
export const SET_GLOBAL_ROUTE = 'SET_GLOBAL_ROUTE'
export const SET_GLOBAL_MUTED = 'SET_GLOBAL_MUTED'
export const SET_GLOBAL_MESSAGE = 'SET_GLOBAL_MESSAGE'
export const SET_GLOBAL_ORDER = 'SET_GLOBAL_ORDER'
export const CLOSE_GLOBAL_WINDOW = 'CLOSE_GLOBAL_WINDOW'

//comments
export const GET_COMMENTS = 'GET_COMMENTS'
export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS'
export const SET_COMMENT_TAB_NAME = 'SET_COMMENT_TAB_NAME'

//chat
export const GET_CHAT = 'GET_CHAT'
export const GET_CHATS = 'GET_CHATS'

//shops
export const GET_MAIN_SHOPES = 'GET_MAIN_SHOPES'
export const GET_SHOPS = 'GET_SHOPS'
export const GET_ALL_SHOPS = 'GET_ALL_SHOPS'
export const GET_SHOP = 'GET_SHOP'
export const GET_OPENED = 'GET_OPENED'
export const SET_PAGINATION_SHOPS = 'SET_PAGINATION_SHOPS'
export const SET_SHOPS_SORTING = 'SET_SHOPS_SORTING'
export const SET_SHOPS_OPENED = 'SET_SHOPS_OPENED'

//events
export const GET_MAIN_EVENTS = 'GET_MAIN_EVENTS'
export const GET_USER_EVENTS = 'GET_USER_EVENTS'
export const GET_EVENTS = 'GET_EVENTS'
export const GET_EVENT = 'GET_EVENT'
export const SET_EVENTS_DATE = 'SET_EVENTS_DATE'
export const SET_EVENTS_TYPE = 'SET_EVENTS_TYPE'
export const SET_EVENTS_CURRENT = 'SET_EVENTS_CURRENT'
export const GET_EVENT_COMMENTS = 'GET_EVENT_COMMENTS'

//sorts
export const GET_MAIN_SORTS = 'GET_MAIN_SAD_SORTS'
export const GET_SORTS = 'GET_SORTS'
export const GET_SORT = 'GET_SORT'
export const SET_PAGINATION_SORTS = 'SET_PAGINATION_SORTS'
export const SET_SORTS_SORTING = 'SET_SORTS_SORTING'

//chemicals
export const GET_CHEMICALS = 'GET_CHEMICALS'
export const GET_CHEMICAL = 'GET_CHEMICAL'
export const SET_PAGINATION_CHEMICALS = 'SET_PAGINATION_CHEMICALS'
export const SET_CHEMICAL_SORTING = 'SET_CHEMICAL_SORTING'

//pests
export const GET_PEST = 'GET_PEST'
export const GET_PESTS = 'GET_PESTS'
export const SET_PAGINATION_PESTS = 'SET_PAGINATION_PESTS'

//diseases
export const GET_DISEASE = 'GET_DISEASE'
export const GET_DISEASES = 'GET_DISEASES'
export const SET_PAGINATION_DISEASES = 'SET_PAGINATION_DISEASES'

//notes
export const GET_NOTE = 'GET_NOTE'
export const GET_NOTES = 'GET_NOTES'
export const SET_PAGINATION_NOTES = 'SET_PAGINATION_NOTES'

//cultures
export const GET_CULTURE_PREVIEW = 'GET_CULTURE_PREVIEW'
export const GET_CULTURES = 'GET_CULTURES'
export const SET_PAGINATION_CULTURES = 'SET_PAGINATION_CULTURES'

//filters
export const EMPTY_FILTER = 'EMPTY_FILTER'
export const SET_CURRENT_FILTER = 'SET_CURRENT_FILTER'
export const GET_CURRENT_FILTER = 'GET_CURRENT_FILTER'
export const SET_CURRENT_FILTER_TYPE = 'SET_CURRENT_FILTER_TYPE'

//Drawer options
export const GET_DRAWER_POSITION = "GET_DRAWER_POSITION"
export const SET_DRAWER_POSITION = "SET_DRAWER_POSITION"

//Params
export const SET_CULTURE_PARAM_TYPE = "SET_DRAWER_POSITION"
export const CLEAR_CULTURE_PARAM_TYPE = "CLEAR_CULTURE_PARAM_TYPE"